INSERT INTO items (name, price, calories) VALUES ('Burger', 5, 400);
INSERT INTO items (name, price, calories) VALUES ('Pizza', 6, 500);
INSERT INTO items (name, price, calories) VALUES ('Salad', 4, 200);
INSERT INTO items (name, price, calories) VALUES ('Sushi', 7, 600);
INSERT INTO items (name, price, calories) VALUES ('Taco', 3, 300);
INSERT INTO items (name, price, calories) VALUES ('Burrito', 4, 400);
INSERT INTO items (name, price, calories) VALUES ('Fries', 2, 300);
INSERT INTO items (name, price, calories) VALUES ('Ice Cream', 3, 400);
INSERT INTO items (name, price, calories) VALUES ('Steak', 8, 700);
INSERT INTO items (name, price, calories) VALUES ('Chicken', 6, 500);
INSERT INTO items (name, price, calories) VALUES ('Fish', 7, 600);
